#!/usr/bin/env python


dna ='GAACTCCAAAAATGAAAACATAGTAGCAATCAAAGCATCCCACTATTTTTTGTCTCTCGTTTCATTAGCGTTGTAAATTACTGATACCCTACTATACCTCTACAAGGCCTTTGTCATCTTTTTACTCAAGTGTGAAATCATCACTTATTGTATGAAGGATGAGCTTTCCGTTCGCTAGTTTGCTGAAAAGGCCTTCTGCAATAAGCTCTCTATTATCTTTAAAAAAACCTGGTTCCTGGTCTTCCATTCTGCTAAAAGCTGTAGGGGTTTTATCACGAGATTCCCGTTGGCATTCTGACTTATTAAAAATGCTTACAGAAGAAATGGATTCTTTAAATGGTCAAATTAATACGTGGACAGATAATAATCCTTTATTAGATGAAATTACGAAGCCATACAGAAAATCTTCAACTCGTTTTTTTCATCCGCTTCTTGTACTTCTAATGTCTAGAGCATCAGTAAATGGGGATCCACCGAGTCAGCAACTATTTCAAAGGTACAAACAACTTGCCCGTGTAACAGAATTGATTCATGCTGCCAATATAATTCATATTAATATTGGAGAAGAACAAAGCAACGAACAGATTAAACTTGCAACGTTGGTTGGAGATTATTTACTCGGAAAGGCGTCTGTTGATTTAGCACATTTAGAAAACAACGCTATTACAGAAATTATGGCTTCTGTTATTGCAAACTTAGTTGAAGGGCACTTCGGAAGCCGACAAAATGGCTCTGTTGGTTTGTCAAACGAACGAACCATCCTTCTGCAATCAGCCTTTATGCCAGCAAAGGCATGTTTATGCGCAAGCATATTGAATAACTCATCACAATACATTAATGATGCGTGTTTCAATTATGGAAAATTTCTAGGCTTATCGCTGCAACTGGCCCATAAGCCTGTATCTCCTGACGCCCAAGTTTTGCAAAAGAATAATGACATTTTGAAAACATATGTTGAGAATGCCAAGAGCTCATTGTCTGTTTTCCCCGATATAGAGGCTAAGCAAGCTCTCATGGAAATCGCTAATAGTGTTTCGAAGTAATCGACAGGTATTGTATCCTGGATTAATATTAGGGTGGCTCATGCATGCTCGTGCAATCGTAACAAATATGTCTTTCTTTTACGAATTTTAACGCTTCAATATAAATCATATTTTTCCTCA'

count = set(dna)
print(count)

#Acount=0
#for A in dna:
#	dna.count('A')
#	Acount += 1
#print(Acount)

Acount =0
Tcount=0
Ccount=0
Gcount=0

for nucleo in dna:
	if nucleo == 'A':
		Acount += 1
	elif nucleo == 'C':
		Ccount += 1
	elif nucleo == 'T':
		Tcount += 1
	else:
		Gcount += 1

print('A', Acount, 'C', Ccount, 'T', Tcount, 'G', Gcount)

nt_dict = {'A':Acount, 'T':Tcount, 'G':Gcount, 'C':Ccount}
print('nt_dict', nt_dict)

nt_values = dict.values(nt_dict)
nt_sum= sum(nt_values)
print(nt_sum)

print((Ccount+Gcount)/nt_sum)

#GC_content = sum(Ccount+Gcount)
#print(GC_content)

print('debugging sum')
print(type(nt_values))
print(type(Ccount))

Clist = [Ccount, Gcount]
sum2 = sum(Clist)
print(sum2)
print(type(Clist))

